---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myrepset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: welcomeapp
  template:
    metadata:
      name: myfirstpod
      labels:
        app: welcomeapp
    spec:
      containers:
      - name: myfirstcontainer
        image: dekstro/myapp
        ports:
        - containerPort: 8501
...
---
apiVersion: v1
kind: Service
metadata:
  name: myfirstservice
spec:
  type: NodePort
  selector:
    app: welcomeapp
  ports:
  - port: 80
    targetPort: 8501
...
