---
apiVersion: v1
kind: Pod
metadata:
  name: myfirstpod
  labels:
    app: welcomeapp
spec:
  containers:
  - image: dekstro/myapp
    name: myfirstcontainer
    ports:
    - containerPort: 8501
...
---
apiVersion: v1
kind: Service
metadata:
  name: myfirstservice
spec:
  type: NodePort
  selector:
    app: welcomeapp
  ports:
  - port: 80
    targetPort: 8501
